# Generated by Django 4.0.3 on 2022-03-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testemonial',
            name='discription',
        ),
        migrations.AddField(
            model_name='testemonial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
