# Generated by Django 4.0.3 on 2022-03-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_remove_testemonial_discription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='Answer',
        ),
        migrations.AddField(
            model_name='faq',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
