# Generated by Django 4.0.3 on 2022-03-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceRange',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
